#!/usr/bin/env node
/* Static site generator for skythomasgidge.com.
   Reads assets/data.js (the single content source) and injects escaped,
   pre-rendered HTML + SEO/social meta into each page between BUILD markers.
   The deployed pages therefore contain real content in source HTML; the
   browser only runs one small enhancement script (site.js).
   Pure Node, no dependencies. Run: npm run build */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const SITE = "https://skythomasgidge.com";

// ---- load content ----
global.window = {};
require(path.join(ROOT, "assets", "data.js"));
const S = global.window.SKY;
// full-text Shenzhen Daily clips (generated by scripts/import-clips.js)
require(path.join(ROOT, "assets", "articles.js"));
const ARTICLES = global.window.SKY_ARTICLES || [];
const artByDate = new Map(ARTICLES.map((a) => [a.date, a]));     // clip lookup by date
const sdByDate = new Map(S.writing.filter((w) => w.source === "sd").map((w) => [w.date, w]));
const clipHref = (a) => `clips/${a.slug}.html`;
const clipAbs = (a) => SITE + "/" + clipHref(a);

// ---- escaping (treat data as untrusted) ----
const esc = (s) => String(s == null ? "" : s)
  .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
  .replace(/"/g, "&quot;").replace(/'/g, "&#39;");
// attribute value; also neutralise javascript: in url-ish attrs
const attr = (s) => esc(s);
const url = (s) => {
  const v = String(s == null ? "" : s).trim();
  return /^\s*javascript:/i.test(v) ? "#" : esc(v);
};

// ---- per-page SEO config ----
const META = {
  "index.html": { path: "/", title: "Sky Thomas Gidge — video editor, photographer, journalist",
    desc: "Sky Thomas Gidge — video editor, photographer and journalist between Shenzhen and Los Angeles. Night photography, investigative writing, and a kit of small AI tools." },
  "writing.html": { path: "/writing.html", title: "Writing — Sky Thomas Gidge",
    desc: "Journalism by Sky Thomas Gidge — features, investigations, breaking news and street portraits from Shenzhen, published in Shenzhen Daily and That's Magazines, 2015–2018." },
  "photography.html": { path: "/photography.html", title: "Photography — Sky Thomas Gidge",
    desc: "Night photography and street work by Sky Thomas Gidge, shot mostly in Shenzhen with some Los Angeles." },
  "shenzhen-daily.html": { path: "/shenzhen-daily.html", title: "Shenzhen Daily Archive — Sky Thomas Gidge",
    desc: "Sky Thomas Gidge's Shenzhen Daily byline archive — staff reporting from Shenzhen, 2015–2016: breaking news, business and expat-life features." },
  "ai-tools.html": { path: "/ai-tools.html", title: "AI Tools — Sky Thomas Gidge",
    desc: "AI tools and experiments by Sky Thomas Gidge — autonomous agents, a bilingual newsletter, and Claude-assisted video and writing workflows." }
};
const OG_IMAGE = SITE + "/og-image.jpg";

function headMeta(file) {
  const m = META[file];
  const canonical = SITE + m.path;
  return [
    `<link rel="icon" href="/favicon.svg">`,
    `<meta name="description" content="${attr(m.desc)}">`,
    `<link rel="canonical" href="${url(canonical)}">`,
    `<meta property="og:type" content="website">`,
    `<meta property="og:site_name" content="Sky Thomas Gidge">`,
    `<meta property="og:title" content="${attr(m.title)}">`,
    `<meta property="og:description" content="${attr(m.desc)}">`,
    `<meta property="og:url" content="${url(canonical)}">`,
    `<meta property="og:image" content="${url(OG_IMAGE)}">`,
    `<meta name="twitter:card" content="summary_large_image">`,
    `<meta name="twitter:title" content="${attr(m.title)}">`,
    `<meta name="twitter:description" content="${attr(m.desc)}">`,
    `<meta name="twitter:image" content="${url(OG_IMAGE)}">`,
    `<noscript><style>.rv{opacity:1 !important;transform:none !important}</style></noscript>`
  ].map(l => "  " + l).join("\n");
}

// ---- renderers (markup mirrors the former runtime templates) ----
function photoCell(p, i, withLand) {
  const cls = "cell" + (withLand && p.o === "l" ? " land" : "") + (p.fit === "contain" ? " contain" : "");
  const cap = esc(p.cap) + (p.loc ? " · " + esc(p.loc) : "");
  return `<div class="${cls}" data-lb="photos" data-full="${url(p.src)}" data-cap="${attr(p.cap)}" data-loc="${attr(p.loc || "")}">`
    + `<img src="${url(p.src)}" alt="${attr(p.cap)}" loading="lazy"><div class="ov"></div>`
    + `<span class="n">${String(i + 1).padStart(2, "0")}</span>`
    + `<span class="cp">${cap}</span></div>`;
}
const photoGrid = (photos, withLand) => photos.map((p, i) => photoCell(p, i, withLand)).join("\n");

// The article a writing entry points to: prefer our on-site full-text clip,
// then the original publication, then the magazine PDF. Thumb + title share it.
function articleLink(w) {
  const clip = artByDate.get(w.date);
  if (clip) return { href: clipHref(clip), ext: false };
  if (w.site) return { href: w.site, ext: true };
  if (w.pdf)  return { href: w.pdf,  ext: true };
  return null;
}
// magazine PDFs are pre-rendered to static thumbnails by scripts/render-pdf-thumbs.js
const pdfThumb = (pdf) => "uploads/thumbs/" + String(pdf).replace(/^.*\//, "").replace(/\.pdf$/i, ".jpg");
function thumbHtml(w) {
  let body;
  if (w.img) body = `<img src="${url(w.img)}" alt="" loading="lazy">`;
  else if (w.pdf) body = `<img class="pdf" src="${url(pdfThumb(w.pdf))}" alt="" loading="lazy">`;
  else return "";
  const L = articleLink(w);
  if (!L) return `<div class="w-thumb thumb-loaded">${body}</div>`;
  const ext = L.ext ? ` target="_blank" rel="noopener"` : "";
  return `<a class="w-thumb thumb-loaded" href="${url(L.href)}"${ext} aria-label="${attr("Read: " + (w.t || ""))}">${body}</a>`;
}
function writingActs(w) {
  let a = "";
  if (w.site) a += `<a href="${url(w.site)}" target="_blank" rel="noopener">Read it <span class="ar">↗</span></a>`;
  if (w.pdf) a += `<a href="${url(w.pdf)}" target="_blank" rel="noopener">Magazine PDF <span class="ar">↗</span></a>`;
  if (w.censored) a += `<span class="censored">Censored — print only</span>`;
  return a;
}
function writingTitle(w) {
  const L = articleLink(w);
  if (!L) return `<div class="wt">${esc(w.t)}</div>`;
  const ext = L.ext ? ` target="_blank" rel="noopener"` : "";
  return `<a class="wt" href="${url(L.href)}"${ext}>${esc(w.t)}</a>`;
}
// homepage writing row (body is an unclassed div)
function homeWritingRow(w) {
  const hasThumb = !!(w.pdf || w.img);
  const cls = "w" + (w.feat ? " feat" : "") + (hasThumb ? " has-thumb" : "");
  return `<div class="${cls}">${thumbHtml(w)}
  <div><div class="wk">${esc(w.kicker)}</div>
  ${writingTitle(w)}
  <div class="wd">${esc(w.d || "")}</div>${w.note ? `<div class="wn">${esc(w.note)}</div>` : ""}</div>
  <div class="wside"><div class="wp">${esc(w.pub || "")}</div><div class="wacts">${writingActs(w)}</div></div>
</div>`;
}
// writing-page row (body is .w-body, includes date; .rv for reveal)
function fullWritingRow(w) {
  const hasThumb = !!(w.pdf || w.img);
  const cls = "w rv" + (w.feat ? " feat" : "") + (hasThumb ? " has-thumb" : "");
  return `<div class="${cls}">${thumbHtml(w)}
  <div class="w-body">
    <div class="wk">${esc(w.kicker)}</div>
    ${writingTitle(w)}
    <div class="wd">${esc(w.d || "")}</div>
    ${w.note ? `<div class="wn">${esc(w.note)}</div>` : ""}
    ${w.date ? `<div class="wdate">${esc(w.date)}</div>` : ""}
  </div>
  <div class="wside"><div class="wp">${esc(w.pub || "")}</div><div class="wacts">${writingActs(w)}</div></div>
</div>`;
}
function aiButton(p, liveLabel) {
  if (p.live) return `<a class="live" href="${url(p.live)}" target="_blank" rel="noopener"><span class="dot"></span>${liveLabel}</a>`;
  if (p.link) return `<a class="go" href="${url(p.link)}" target="_blank" rel="noopener">${esc(p.linkText || "Read it")}</a>`;
  return "";
}
const aiShot = (p) => p.img ? `<div class="shot"><img src="${url(p.img)}" alt="${attr(p.t)}" loading="lazy"></div>` : "";
const aiGallery = (p, grp) => p.gallery
  ? `<div class="gallery">${p.gallery.map(g => `<img src="${url(g)}" alt="" loading="lazy" data-lb="${grp}" data-full="${url(g)}">`).join("")}</div>`
  : "";
const aiTags = (p) => `<div class="tags">${p.tags.map(t => `<span>${esc(t)}</span>`).join("")}</div>`;
// homepage AI card (.aic)
function homeAiCard(p, i) {
  const cls = "aic" + (p.live ? " live-card" : "") + (p.span2 ? " span2" : "");
  return `<div class="${cls}">
  <div class="aic-top"><span class="st">${esc(p.status)}</span>${p.metric ? `<span class="mt">${esc(p.metric)}</span>` : ""}</div>
  <h3>${esc(p.t)}</h3><p>${esc(p.d)}</p>
  ${aiShot(p)}${aiGallery(p, "ai-home-" + i)}
  ${aiTags(p)}
  ${aiButton(p, "It's live — have a look ↗")}</div>`;
}
// ai-tools page card (.mcard)
function toolsAiCard(p, i) {
  const cls = "mcard rv" + (p.live ? " live-card" : "") + (p.span2 ? " span2" : "");
  return `<div class="${cls}"><div class="metric"><small>${p.cadence ? "Cadence" : "Result"}</small>${esc(p.metric)}</div>
  <div><div class="st">${esc(p.status)}</div><h3>${esc(p.t)}</h3></div>
  <p>${esc(p.d)}</p>
  ${aiShot(p)}${aiGallery(p, "ai-tools-" + i)}
  <div class="foot"><div class="tags">${p.tags.map(t => `<span>${esc(t)}</span>`).join("")}</div>${aiButton(p, "It's live ↗")}</div></div>`;
}
function archiveRow(w) {
  const year = (w.date || "").slice(0, 4) || "Undated";
  const isAward = /excellence|prize|award/i.test(w.note || "");
  const awardTag = isAward ? `<span class="award">★ Prize-winning</span>` : "";
  const clip = artByDate.get(w.date);   // full text hosted on this domain?
  let open, close, tag;
  if (clip) {                           // link to our own indexable page
    open = `<a class="arow rv" href="${url(clipHref(clip))}">`;
    close = `</a>`;
    tag = `<span class="go">Read full text →</span>`;
  } else if (w.site) {                  // no local copy — link to the original
    open = `<a class="arow rv" href="${url(w.site)}" target="_blank" rel="noopener">`;
    close = `</a>`;
    tag = `<span class="go">Read on szdaily ↗</span>`;
  } else {
    open = `<div class="arow rv">`;
    close = `</div>`;
    tag = `<span class="printonly">Print only</span>`;
  }
  return { year, html: `${open}
  <div class="date">${esc(w.date || "")}</div>
  <div class="main"><div class="k">${esc(w.kicker || "News")}</div><h3>${esc(w.t)}</h3>${w.note ? `<div class="by">${esc(w.note)}</div>` : ""}${w.d ? `<div class="desc">${esc(w.d)}</div>` : ""}</div>
  <div class="side">${awardTag}${tag}</div>${close}` };
}

// ---- contact + socials (shared by clip pages and the SD index) ----
const SOCIAL_DEFS = [["LinkedIn", "linkedin"], ["Instagram", "instagram"], ["Twitter / X", "twitter"]];
function socialUrls() {
  const s = S.identity.social || {};
  return SOCIAL_DEFS.map(([, k]) => s[k]).filter(Boolean);
}
function socialLinks() {
  const s = S.identity.social || {};
  return SOCIAL_DEFS.filter(([, k]) => s[k])
    .map(([label, k]) => `<a href="${url(s[k])}" target="_blank" rel="noopener me">${esc(label)}</a>`)
    .join("");
}
function contactBlock() {
  const id = S.identity;
  return `<div class="contact">
  <div class="ct-h">Get in touch</div>
  <a class="ct-mail" href="mailto:${attr(id.email)}">${esc(id.email)}</a>
  <div class="ct-social">${socialLinks()}</div>
</div>`;
}

// ---- clip (full-text article) pages ----
const J = (s) => String(s == null ? "" : s).replace(/</g, "\\u003c"); // JSON-LD safety
function bylineText(b) {
  const p = String(b || "Sky Gidge").split(",").map((s) => s.trim()).filter(Boolean);
  return p.length > 1 ? p.slice(0, -1).join(", ") + " and " + p[p.length - 1] : p[0];
}
function clipDesc(a, row) {
  if (row && row.d) return row.d;
  const first = (a.paras[0] || "").replace(/\s+/g, " ").trim();
  return first.length > 155 ? first.slice(0, 152).replace(/\s+\S*$/, "") + "…" : first;
}
function clipJsonLd(a, row, title, desc) {
  const ld = {
    "@context": "https://schema.org", "@type": "NewsArticle",
    headline: title, datePublished: a.date, dateline: "Shenzhen, China", inLanguage: "en",
    author: { "@type": "Person", name: "Sky Thomas Gidge", url: SITE + "/", sameAs: socialUrls() },
    publisher: { "@type": "Organization", name: "Shenzhen Daily" },
    mainEntityOfPage: clipAbs(a),
    description: desc
  };
  if (a.source_url) ld.isBasedOn = a.source_url;   // points at the original publication
  return `<script type="application/ld+json">${J(JSON.stringify(ld))}</script>`;
}
function renderClip(a) {
  const row = sdByDate.get(a.date) || {};
  const title = row.t || a.fallbackTitle || a.slug;
  const desc = clipDesc(a, row);
  const isAward = /excellence|prize|award/i.test(row.note || "");
  const body = a.paras.map((p) => `      <p>${esc(p)}</p>`).join("\n");
  const orig = a.source_url
    ? `<a class="orig" href="${url(a.source_url)}" target="_blank" rel="noopener">View the original on Shenzhen Daily <span class="ar">↗</span></a>`
    : "";
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(title)} — Sky Thomas Gidge</title>
  <meta name="description" content="${attr(desc)}">
  <link rel="canonical" href="${url(clipAbs(a))}">
  <link rel="icon" href="../favicon.svg">
  <meta name="author" content="Sky Thomas Gidge">
  <meta property="article:published_time" content="${attr(a.date)}">
  <meta property="og:type" content="article">
  <meta property="og:site_name" content="Sky Thomas Gidge">
  <meta property="og:title" content="${attr(title)}">
  <meta property="og:description" content="${attr(desc)}">
  <meta property="og:url" content="${url(clipAbs(a))}">
  <meta property="og:image" content="${url(OG_IMAGE)}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="${attr(title)}">
  <meta name="twitter:description" content="${attr(desc)}">
  <meta name="twitter:image" content="${url(OG_IMAGE)}">
  ${clipJsonLd(a, row, title, desc)}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@0,6..72,400;0,6..72,500;0,6..72,600;1,6..72,400&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<style>
  :root{
    --bg:#121110; --panel:#1a1816; --ink:#ece7dc; --soft:#9a9286;
    --faint:#8c8275; --line:rgba(236,231,220,.12); --line-2:rgba(236,231,220,.07);
    --accent:#d4663a; --mono:"JetBrains Mono",ui-monospace,monospace;
    --serif:"Newsreader",Georgia,serif; --sans:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;
  }
  *{margin:0;padding:0;box-sizing:border-box}
  .sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
  :focus-visible{outline:2px solid var(--accent);outline-offset:3px}
  html{scroll-behavior:smooth}
  body{background:var(--bg);color:var(--ink);font-family:var(--sans);-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility}
  ::selection{background:var(--accent);color:#fff}
  a{color:inherit;text-decoration:none}
  .wrap{max-width:720px;margin:0 auto;padding:0 40px}
  .lab{font-family:var(--mono);font-size:11px;letter-spacing:.18em;text-transform:uppercase;color:var(--soft)}
  .top{position:fixed;top:0;left:0;right:0;z-index:60;height:62px;display:flex;align-items:center;
    background:color-mix(in srgb,var(--bg) 82%,transparent);backdrop-filter:blur(10px);border-bottom:1px solid var(--line-2)}
  .top .wrap{display:flex;align-items:center;justify-content:space-between;max-width:1000px;width:100%}
  .back{display:inline-flex;align-items:center;gap:9px;font-family:var(--mono);font-size:11px;letter-spacing:.14em;
    text-transform:uppercase;color:var(--soft);transition:color .2s,gap .2s}
  .back:hover{color:var(--ink);gap:12px}
  .back .ar{color:var(--accent)}
  .top nav{display:flex;gap:24px}
  .top nav a{font-family:var(--mono);font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:var(--soft);transition:color .2s}
  .top nav a:hover{color:var(--ink)}
  article{padding:112px 0 0}
  .crumb{font-family:var(--mono);font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:var(--faint);margin-bottom:18px}
  .crumb a:hover{color:var(--accent)}
  .k{font-family:var(--mono);font-size:10px;letter-spacing:.16em;text-transform:uppercase;color:var(--accent);margin-bottom:14px}
  h1{font-family:var(--serif);font-size:clamp(30px,4.4vw,46px);font-weight:500;letter-spacing:-.02em;line-height:1.08}
  .meta{display:flex;flex-wrap:wrap;gap:8px 16px;align-items:center;margin:22px 0 6px;
    font-family:var(--mono);font-size:11px;letter-spacing:.06em;color:var(--soft);
    padding-bottom:26px;border-bottom:1px solid var(--line-2)}
  .meta .award{color:var(--accent);border:1px solid rgba(212,102,58,.4);padding:4px 8px;letter-spacing:.1em;text-transform:uppercase}
  .body{padding:34px 0 8px}
  .body p{font-family:var(--serif);font-size:18px;line-height:1.72;color:#e3ddd0;margin:0 0 22px}
  .body p:first-child::first-letter{font-size:3.1em;float:left;line-height:.84;padding:6px 10px 0 0;color:var(--accent);font-weight:500}
  .orig{display:inline-flex;align-items:center;gap:9px;margin:14px 0 0;font-family:var(--mono);font-size:11px;
    letter-spacing:.1em;text-transform:uppercase;color:var(--soft);border:1px solid var(--line-2);padding:11px 15px;transition:all .2s}
  .orig:hover{border-color:var(--accent);color:#fff}
  .orig .ar{color:var(--accent)}
  .contact{margin-top:18px;padding:30px 0 0;border-top:1px solid var(--line-2)}
  .ct-h{font-family:var(--mono);font-size:11px;letter-spacing:.16em;text-transform:uppercase;color:var(--faint);margin-bottom:12px}
  .ct-mail{font-family:var(--serif);font-size:21px;color:var(--ink);border-bottom:1px solid var(--line);transition:color .2s,border-color .2s}
  .ct-mail:hover{color:var(--accent);border-color:var(--accent)}
  .ct-social{display:flex;flex-wrap:wrap;gap:10px 22px;margin-top:18px}
  .ct-social a{font-family:var(--mono);font-size:11px;letter-spacing:.1em;text-transform:uppercase;color:var(--soft);transition:color .2s}
  .ct-social a:hover{color:var(--accent)}
  footer{padding:60px 0 56px;margin-top:46px;border-top:1px solid var(--line-2)}
  .colophon{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap}
  @media(max-width:760px){.wrap{padding:0 22px}.top nav{display:none}.body p{font-size:17px}}
</style>
</head>
<body>
  <div class="top"><div class="wrap">
    <a href="../shenzhen-daily.html" class="back"><span class="ar">←</span><span>Shenzhen Daily</span></a>
    <nav>
      <a href="../writing.html">Writing</a>
      <a href="../photography.html">Photography</a>
      <a href="../index.html#contact">Contact</a>
    </nav>
  </div></div>
  <main><div class="wrap">
    <article>
      <div class="crumb"><a href="../writing.html">Writing</a> / <a href="../shenzhen-daily.html">Shenzhen Daily</a></div>
      ${row.kicker ? `<div class="k">${esc(row.kicker)}</div>` : ""}
      <h1>${esc(title)}</h1>
      <div class="meta">
        <span>By ${esc(bylineText(a.byline))}</span>
        <span>${esc(a.date)}</span>
        <span>Shenzhen Daily</span>
        ${isAward ? `<span class="award">★ Prize-winning</span>` : ""}
      </div>
      <div class="body">
${body}
      </div>
      ${orig}
      ${contactBlock()}
    </article>
  </div></main>
  <footer><div class="wrap">
    <div class="colophon lab"><span>Sky Thomas Gidge © 2026</span><span>Originally published in Shenzhen Daily, ${esc((a.date || "").slice(0, 4))}</span></div>
  </div></footer>
</body>
</html>
`;
}

// ---- build sections per page ----
function groupedWriting(rowFn) {
  let out = "", last = null;
  S.writing.forEach(w => {
    const g = w.group || "More";
    if (g !== last) { out += `<div class="wgroup">${esc(g)}</div>\n`; last = g; }
    out += rowFn(w) + "\n";
  });
  return out;
}
function sections(file) {
  if (file === "index.html") {
    const intro = esc(S.introLine).replace("usually do.", `<span class='q'>usually do.</span>`);
    const homePhotos = S.photos.filter(p => p.home).sort((a, b) => (a.homeOrder || 99) - (b.homeOrder || 99));
    const home = S.writing.filter(w => w.home).sort((a, b) => (a.homeOrder || 99) - (b.homeOrder || 99));
    const restGroups = [...new Set(S.writing.filter(w => !w.home).map(w => w.group))].length;
    const wfoot = S.writing.length > home.length
      ? `<div class="wlist-foot"><a class="more" href="writing.html"><span>See ${S.writing.length - home.length} more articles</span><span class="ar">→</span></a><span class="lab">a selection across ${restGroups} sections</span></div>`
      : "";
    return {
      introLine: intro,
      pgCount: esc(S.photos.length + " frames · night · Shenzhen / LA"),
      pg: photoGrid((homePhotos.length ? homePhotos : S.photos.slice(0, 6)), false),
      moreLabel: "See all " + S.photos.length,
      award: `<span class="dot"></span><div><div class="k">${esc(S.award.kicker)} · ${esc(S.award.pub)}</div><div class="t">${esc(S.award.t)}</div></div>`,
      wlist: home.map(homeWritingRow).join("\n") + (wfoot ? "\n" + wfoot : ""),
      aigrid: S.ai.map(homeAiCard).join("\n"),
      clients: S.identity.clients.map(c => `<li>${esc(c)}</li>`).join(""),
      social: socialLinks()
    };
  }
  if (file === "photography.html") return {
    count: esc(S.photos.length + " frames · night · Shenzhen / LA"),
    pg: photoGrid(S.photos, true),
    social: socialLinks()
  };
  if (file === "writing.html") return {
    articleCount: `${S.writing.length} articles`,
    award: `<span class="dot"></span><div><div class="k">${esc(S.award.kicker)} · ${esc(S.award.pub)}</div><div class="t">${esc(S.award.t)}</div></div>`,
    wlist: groupedWriting(fullWritingRow),
    social: socialLinks()
  };
  if (file === "ai-tools.html") return { mgrid: S.ai.map(toolsAiCard).join("\n"), social: socialLinks() };
  if (file === "shenzhen-daily.html") {
    const sd = S.writing.filter(w => w.source === "sd").sort((a, b) => (a.date || "").localeCompare(b.date || ""));
    let out = "", last = null;
    sd.forEach(w => { const r = archiveRow(w); if (r.year !== last) { out += `<div class="yr">${esc(r.year)}</div>\n`; last = r.year; } out += r.html + "\n"; });
    return { archive: out, contact: contactBlock() };
  }
  return {};
}

// ---- inject between <!--BUILD:name-->...<!--/BUILD:name--> markers ----
function inject(html, name, content) {
  const re = new RegExp(`(<!--BUILD:${name}-->)[\\s\\S]*?(<!--/BUILD:${name}-->)`);
  if (!re.test(html)) { console.warn(`  ! marker BUILD:${name} not found`); return html; }
  return html.replace(re, `$1\n${content}\n$2`);
}

let built = 0;
for (const file of Object.keys(META)) {
  const fp = path.join(ROOT, file);
  let html = fs.readFileSync(fp, "utf8");
  html = inject(html, "head", headMeta(file));
  const secs = sections(file);
  for (const [name, content] of Object.entries(secs)) html = inject(html, name, content);
  fs.writeFileSync(fp, html);
  built++;
  console.log(`  built ${file}`);
}

// ---- clip (full-text article) pages ----
const clipsDir = path.join(ROOT, "clips");
if (!fs.existsSync(clipsDir)) fs.mkdirSync(clipsDir);
const clipPaths = [];
for (const a of ARTICLES) {
  fs.writeFileSync(path.join(clipsDir, a.slug + ".html"), renderClip(a));
  clipPaths.push("/" + clipHref(a));
  built++;
}
console.log(`  built ${ARTICLES.length} clip pages -> clips/`);

// ---- sitemap.xml ----
const today = process.env.BUILD_DATE || ""; // optional; omit lastmod if unset
const allPaths = [...Object.values(META).map(m => m.path), ...clipPaths];
const urls = allPaths.map(p =>
  `  <url><loc>${SITE}${p}</loc>${today ? `<lastmod>${today}</lastmod>` : ""}</url>`).join("\n");
fs.writeFileSync(path.join(ROOT, "sitemap.xml"),
  `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`);
console.log(`  wrote sitemap.xml (${allPaths.length} urls)`);

// ---- warn if social placeholders remain ----
if (socialUrls().some(u => /REPLACE_ME/.test(u)))
  console.warn("\n  ⚠ data.js identity.social still has REPLACE_ME — set real LinkedIn/Instagram/Twitter URLs before deploying.");

console.log(`\n  build complete: ${built} pages.`);
