#!/usr/bin/env node
/* One-time / local import step for the Shenzhen Daily clips.
   Reads the locally-archived article Markdown (full text + frontmatter) from the
   vault archive and writes a committed, self-contained data file
   assets/articles.js (window.SKY_ARTICLES). The site build (build.js) consumes
   ONLY that file, so the deploy/CI build never needs the out-of-repo archive.

   Re-run this only when the archive gains/edits articles:
     node scripts/import-clips.js  [path-to-archive-folder]
   Pure Node, no dependencies. */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const ARCHIVE = process.argv[2] ||
  "/Users/sky/Desktop/CLAUDE/2026 WEBSITE/WRITING/Shenzhen Daily Archive/archive";

// Folders that are NOT a Sky byline article page:
//  - 2017-04-21… is the awards-announcement piece (proof of the prize), by another reporter.
const SKIP = new Set(["2017-04-21-daily-staff-win-six-news-prizes"]);

// minimal frontmatter reader (the subset these files use)
function parseFront(raw) {
  const m = raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!m) return { fm: {}, body: raw };
  const fm = {};
  for (const line of m[1].split("\n")) {
    const kv = line.match(/^(\w+):\s*(.*)$/);
    if (!kv) continue;
    let [, k, v] = kv;
    v = v.trim();
    if (/^\[.*\]$/.test(v)) {
      fm[k] = v.slice(1, -1).split(",").map(s => s.trim().replace(/^"|"$/g, "")).filter(Boolean);
    } else {
      fm[k] = v.replace(/^"|"$/g, "");
    }
  }
  return { fm, body: m[2] };
}

// body Markdown -> array of clean paragraph strings
function paragraphs(body) {
  return body
    .replace(/^#\s+.*$/m, "")                 // drop the duplicated H1 title line
    .split(/\n{2,}/)
    .map(p => p.replace(/\s+/g, " ").trim())
    .map(p => p.replace(/\(Continued (?:on|from) P\d+\)/gi, "").trim())
    .map(p => p.replace(/\s*\([^)]*\?\?\?[^)]*\)/g, "").trim())  // strip leaked draft notes, e.g. "(source???…)"
    .filter(p => p && !/^#/.test(p));
}

const dirs = fs.readdirSync(ARCHIVE)
  .filter(d => !SKIP.has(d) && fs.existsSync(path.join(ARCHIVE, d, "article.md")))
  .sort();

const articles = dirs.map(d => {
  const raw = fs.readFileSync(path.join(ARCHIVE, d, "article.md"), "utf8");
  const { fm, body } = parseFront(raw);
  return {
    slug: d.replace(/^\d{4}-\d{2}-\d{2}-/, ""),  // drop date prefix for a clean URL
    date: fm.date || d.slice(0, 10),
    byline: fm.byline || "Sky Gidge",
    sections: fm.sections || [],
    source_url: fm.source_url || "",
    fallbackTitle: fm.title || "",
    paras: paragraphs(body)
  };
});

const out = "/* GENERATED by scripts/import-clips.js — do not edit by hand.\n" +
  "   Full text of Sky's archived Shenzhen Daily articles, for static page generation. */\n" +
  "window.SKY_ARTICLES = " + JSON.stringify(articles, null, 2) + ";\n";
fs.writeFileSync(path.join(ROOT, "assets", "articles.js"), out);
console.log(`Wrote assets/articles.js — ${articles.length} articles, ${articles.reduce((n, a) => n + a.paras.length, 0)} paragraphs.`);
